Implement responsive header and burger menu on small screens
reactcebu/website-v2 pull request #22
Opened 2020-10-13 10:40 UTC by jromest

## Description
Implement responsive header and burger menu on small screens

## Summary of Changes
- additional dependencies, install `body-scroll-lock`
- create shared breakpoints
- implement burger menu on a small screen in the header
- fix horizontal and vertical scroll in mobile 

## Screenshots
**Header**
![Screen Shot 2020-10-13 at 6 37 17 PM](https://user-images.githubusercontent.com/25174423/95850285-2d7d5f00-0d83-11eb-8a64-08b895f3ba5a.png)

**Open Menu**
![Screen Shot 2020-10-13 at 6 36 13 PM](https://user-images.githubusercontent.com/25174423/95850178-04f56500-0d83-11eb-9ea4-5cd450cd84f5.png)

Closes #16

2020-10-13 13:11 UTC, dorelljames commented
Thank you for your contribution @jromest but I see one thing that needs to be fixed. I'm not sure if you noticed but the current deploy at https://deploy-preview-22--reactcebu-sitev2.netlify.app/ shows this previous issue we had on the site. See the styling on the newsletter form. 

![image](https://user-images.githubusercontent.com/977413/95864748-6bd14900-0d98-11eb-8574-7b7e8fccffe3.png)

Once that's fixed, I'd be happy to merge it. 😊

2020-10-13 14:47 UTC, jromest commented
Hey @dorelljames, I think you forgot to load ng styled-components plugin in gatsby-config, adding it on the gatsby-config solves the issue. 😄

2020-10-13 15:05 UTC, dorelljames requested changes
Please add the necessary styling to finalize this PR. Thank you so much for your contribution @jromest. Well done. :)

2020-10-13 15:05 UTC, dorelljames commented on src/components/Header/Header.styles.ts
> +  background-color: #fff;
Can you please add a `z-index` of at least a value of 5 to resolve this little overlap issue. :)

![image](https://user-images.githubusercontent.com/977413/95878693-169d3380-0da8-11eb-8ab2-f133b7f7049f.png)

2020-10-14 02:28 UTC, siegblink reviewed
I believe this is good to go although I have yet to test this in my local environment.
Bai @dorelljames your thoughts?

2020-10-14 04:27 UTC, dorelljames commented
I agree with you @siegblink. Thanks. Will merge now. Thanks once again @jromest :)

2020-10-14 04:27 UTC, merged